/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module logicOut_2 (
    input clk,
    input rst,
    output reg signalA,
    output reg signalB,
    output reg signalC
  );
  
  
  
  reg [27:0] M_counterA_d, M_counterA_q = 1'h0;
  reg [28:0] M_counterB_d, M_counterB_q = 1'h0;
  reg [29:0] M_counterC_d, M_counterC_q = 1'h0;
  
  always @* begin
    M_counterC_d = M_counterC_q;
    M_counterB_d = M_counterB_q;
    M_counterA_d = M_counterA_q;
    
    signalA = M_counterA_q[27+0-:1];
    M_counterA_d = M_counterA_q + 1'h1;
    signalB = M_counterB_q[28+0-:1];
    M_counterB_d = M_counterB_q + 1'h1;
    signalC = M_counterC_q[29+0-:1];
    M_counterC_d = M_counterC_q + 1'h1;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_counterA_q <= 1'h0;
      M_counterB_q <= 1'h0;
      M_counterC_q <= 1'h0;
    end else begin
      M_counterA_q <= M_counterA_d;
      M_counterB_q <= M_counterB_d;
      M_counterC_q <= M_counterC_d;
    end
  end
  
endmodule
