/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg spi_miso,
    output reg [1:0] spi_channel,
    output reg avr_rx,
    output reg pinoutA,
    output reg pinoutB,
    output reg pinoutC,
    output reg [23:0] io_led
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_myLogic_signalA;
  wire [1-1:0] M_myLogic_signalB;
  wire [1-1:0] M_myLogic_signalC;
  logicOut_2 myLogic (
    .clk(clk),
    .rst(rst),
    .signalA(M_myLogic_signalA),
    .signalB(M_myLogic_signalB),
    .signalC(M_myLogic_signalC)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    pinoutA = M_myLogic_signalA;
    pinoutB = M_myLogic_signalB;
    pinoutC = M_myLogic_signalC;
    io_led[0+7-:8] = {4'h8{M_myLogic_signalA}};
    io_led[8+7-:8] = {4'h8{M_myLogic_signalB}};
    io_led[16+7-:8] = {4'h8{M_myLogic_signalC}};
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
  end
endmodule
